version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda
  install_kipoi_utils: &install_kipoi_utils
    run:
      name: Install Kipoi Utils
      command: |
        git clone git@github.com:kipoi/kipoiutils.git kipoi_utils_pkg
        cd kipoi_utils_pkg
        pip install '.'
        cd ..
  install_psutils: &install_psutils
    run:
      name: Install psutil
      command: |
        conda install psutil --yes
  install_kipoi_conda: &install_kipoi_conda
    run:
      name: Install kipoi_conda
      command: pip install '.[develop]'
  install_requests: &install_requests
    run:
      name: Install requirements for requests correctly
      command: pip install requests
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        mkdir test-reports
        py.test --cov=kipoi_conda/ tests/ -n 1 --no-cov-on-fail --junitxml=test-reports/junit.xml
  run_coveralls: &run_coveralls
    run:
      name: run coveralls
      command: coveralls || true
  store_test_results: &store_test_results
    store_test_results:
      path: test-reports
  store_test_artifacts: &store_test_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports


jobs:

  test-py36:
    docker:
      - image: continuumio/miniconda3:4.5.12
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_kipoi_utils
      - *install_kipoi_conda
      - *run_tests
      - *run_coveralls
      - *store_test_results
      - *store_test_artifacts


  # build-deploy-docs:
  #   docker:
  #     # - image: continuumio/miniconda3:4.3.14
  #     - image: continuumio/miniconda3:4.5.12
  #     # - image: continuumio/anaconda3:5.0.1
  #     # - image: circleci/python:3.5
  #   working_directory: ~/repo
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - e3:44:16:ec:72:df:ae:59:82:c2:ee:57:4a:52:71:aa
  #     - checkout
  #     - run:
  #         name: Install pip Kipoi
  #         command: pip install git+https://github.com/kipoi/kipoi@master
  #     - run:
  #         name: Install pip kipoi_conda
  #         command: pip install -e .
  #     - run:
  #         name: Install build deps
  #         # use custom pydoc-markdown
  #         command: pip install nbconvert mkdocs git+https://github.com/kipoi/pydoc-markdown@master
  #     - run:
  #         name: Build docs
  #         command: |
  #           cd docs/
  #           mkdir -p theme_dir/img/ipynb/
  #           ./render_ipynb.bash
  #           pydocmd build
  #     - run:
  #         name: Deploy docs
  #         command: .circleci/deploy_docs.bash

workflows:
  version: 2
  test:
    jobs:
      - test-py36
      # - build-deploy-docs:
      #     requires:
      #       - test-py36
      #       - test-py27
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - test_deployment_script
